# build no_std 
b: 
  cargo build

# build std 
bs: 
  cargo build --features std 

# test std
ts: 
  cargo test --features std

# build and run 
br: 
  cargo build --bin test_pid --features std && cargo run --bin test_pid
